version: '3'
services:
        myosdb:
                image: mysql:5.7
                volumes:
                        - mysql_storage1:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: my123
                        MYSQL_USER: pblaze
                        MYSQL_PASSWORD: my1234
                        MYSQL_DATABASE: mydb
        wordpressos:
                image: wordpress:latest
                restart: always
                depends_on:
                        - myosdb
                ports:
                        - 8081:80
                environment:
                        WORDPRESS_DB_HOST: myosdb
                        WORDPRESS_DB_USER: pblaze
                        WORDPRESS_DB_PASSWORD: my1234
                        WORDPRESS_DB_NAME: mydb
                volumes:
                        - wordpress_storage1:/var/www/html
volumes:
        wordpress_storage1:
        mysql_storage1:
 

